AWSTemplateFormatVersion: 2010-09-09
Description: Conditions practice

Parameters:
  MyKeyName:
    Description: Select the key from drop down
    Type: AWS::EC2::KeyPair::KeyName
  EnvironmentName:
    Description: select the Environmen type
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
    ConstraintDescription: must be dev, qa or prod


Mappings:
  MyRegionMap:
    us-east-1:
      HVM64: ami-0742b4e673072066f
    us-west-1:
      HVM64: ami-0577b787189839998

  MyEnvironmentMap:
    dev:
      instanceType: t2.micro
    qa:
      instanceType: t2.medium
    prod:
      instanceType: t2.small           


Resources:
  MyVMInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - MyRegionMap
        - !Ref 'AWS::Region'
        - HVM64
      InstanceType: !FindInMap
        - MyEnvironmentMap
        - !Ref EnvironmentName
        - instanceType
      KeyName: !Ref MyKeyName